// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeZ7YeO7O0PGMEgWF8ZnpqvuTgswtIWu4',
    appId: '1:695906066563:web:778cb1b6f32e59d67d7bb6',
    messagingSenderId: '695906066563',
    projectId: 'messageapp-f1ed7',
    authDomain: 'messageapp-f1ed7.firebaseapp.com',
    storageBucket: 'messageapp-f1ed7.appspot.com',
    measurementId: 'G-8XF1JJZWBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcVGrDLJLOyN095ROrsZhHRsVxKbBrX3I',
    appId: '1:695906066563:android:a850e73a622df73e7d7bb6',
    messagingSenderId: '695906066563',
    projectId: 'messageapp-f1ed7',
    storageBucket: 'messageapp-f1ed7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs5trlVTTq_VRy5-zFgIaxLtzfCQZ2MSA',
    appId: '1:695906066563:ios:431ad99a064b4f417d7bb6',
    messagingSenderId: '695906066563',
    projectId: 'messageapp-f1ed7',
    storageBucket: 'messageapp-f1ed7.appspot.com',
    iosClientId: '695906066563-m8b4ctbio5c3ur29sdk1atlv90msgimg.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs5trlVTTq_VRy5-zFgIaxLtzfCQZ2MSA',
    appId: '1:695906066563:ios:b3c67399037a87277d7bb6',
    messagingSenderId: '695906066563',
    projectId: 'messageapp-f1ed7',
    storageBucket: 'messageapp-f1ed7.appspot.com',
    iosClientId: '695906066563-u7vsnpa11er9cpnd9dg3ueua75eb73q8.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageapp.RunnerTests',
  );
}
